
import java.util.HashSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lmfg0
 */
public class ServiceOptions extends javax.swing.JFrame {

    private Vehiculo infoVehiculo;
    
    /**
     * Creates new form ServiceOptions
     */
    public ServiceOptions() {
        initComponents();
        this.infoVehiculo = new Vehiculo();
    }

    public void setInfoVehiculo(Vehiculo infoVehiculo) {
        this.infoVehiculo = infoVehiculo;
        showInformation();
        handleButtons();
    }
     
    public Vehiculo getVehiculoOptions(){
        return infoVehiculo;
    }
    
    private void showInformation() {
        if (this.infoVehiculo != null && this.infoVehiculo.getVehiculo() != null){
            if (this.infoVehiculo.getVehiculo() == tipoVehiculo.CARRO) {
                radioCarro.setSelected(true);
            }

            if (this.infoVehiculo.getVehiculo() == tipoVehiculo.MOTO) {
                radioMoto.setSelected(true);
            }

            if (this.infoVehiculo.getLavado()== tipoLavado.NORMAL) {
                radioNormal.setSelected(true);
            }
            
            if (this.infoVehiculo.getLavado()== tipoLavado.PREMIUN) {
                radioPremiun.setSelected(true);
            }
            
            if (this.infoVehiculo.getLavado()== tipoLavado.PRESIDENCIAL) {
                radioPresidencial.setSelected(true);
            }
            
            if (this.infoVehiculo.getLavado()== tipoLavado.CON_MASAJE) {
                radioMasaje.setSelected(true);
            }
            
            if (this.infoVehiculo.getPlaca() != null){
                txtPlaca.setText(this.infoVehiculo.getPlaca());
            }
            
            if (this.infoVehiculo.getPropietario() != null){
                txtPropietario.setText(this.infoVehiculo.getPropietario());
            }
        }
    }
    
    private void handleButtons(){
        if (!(this.infoVehiculo != null && this.infoVehiculo.getVehiculo() != null)){
            btnFinalizar.setEnabled(false);
            btnEliminar.setEnabled(false);                     
        } else {
            btnAceptar.setEnabled(false);
            btnCancelar.setEnabled(false);
        }
    }

    private void calcular() {
        double gananciaAdicional = 0;
        double costoAdicional = 10000;

        // Obtener el tipo de lavado y tipo de vehículo
        tipoLavado lavado = this.infoVehiculo.getLavado();
        tipoVehiculo vehiculo = this.infoVehiculo.getVehiculo();

        // Determinar la ganancia base según el tipo de vehículo
        switch (vehiculo) {
            case MOTO:
                this.infoVehiculo.setGanancia(this.infoVehiculo.getGanancia() + 10000);
                break;
            case CARRO:
                this.infoVehiculo.setGanancia(this.infoVehiculo.getGanancia() + 20000);
                break;
        }

        // Determinar la ganancia adicional según el tipo de lavado
        switch (lavado) {
            case NORMAL:
                gananciaAdicional = (vehiculo == tipoVehiculo.MOTO) ? 5000 : 10000;
                break;
            case PREMIUN:
                gananciaAdicional = (vehiculo == tipoVehiculo.MOTO) ? 10000 : 20000;
                break;
            case PRESIDENCIAL:
                gananciaAdicional = (vehiculo == tipoVehiculo.MOTO) ? 20000 : 30000;
                break;
            case CON_MASAJE:
                gananciaAdicional = (vehiculo == tipoVehiculo.MOTO) ? 25000 : 40000;
                break;
        }

        // Actualizar la ganancia y el costo
        this.infoVehiculo.setGanancia(this.infoVehiculo.getGanancia() + gananciaAdicional);
        this.infoVehiculo.setCosto(this.infoVehiculo.getCosto() + costoAdicional);
    }


    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        radioMoto = new javax.swing.JRadioButton();
        radioCarro = new javax.swing.JRadioButton();
        radioNormal = new javax.swing.JRadioButton();
        radioPremiun = new javax.swing.JRadioButton();
        radioPresidencial = new javax.swing.JRadioButton();
        radioMasaje = new javax.swing.JRadioButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione el tipo de vehiculo:");

        jLabel2.setText("Seleccione el tipo de lavado:");

        jLabel3.setText("Placa:");

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        jLabel4.setText("Propietario");

        txtPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPropietarioActionPerformed(evt);
            }
        });

        radioMoto.setText("MOTO");
        radioMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMotoActionPerformed(evt);
            }
        });

        radioCarro.setText("CARRO");
        radioCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCarroActionPerformed(evt);
            }
        });

        radioNormal.setText("NORMAL");
        radioNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNormalActionPerformed(evt);
            }
        });

        radioPremiun.setText("PREMIUM");
        radioPremiun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPremiunActionPerformed(evt);
            }
        });

        radioPresidencial.setText("PRESIDENCIAL");
        radioPresidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPresidencialActionPerformed(evt);
            }
        });

        radioMasaje.setText("CON MASAJE");
        radioMasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMasajeActionPerformed(evt);
            }
        });

        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFinalizar.setText("FINALIZAR");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnFinalizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioPresidencial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(radioNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(radioMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(radioPremiun, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(txtPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(radioMasaje, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMoto)
                    .addComponent(radioCarro))
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioNormal)
                    .addComponent(radioPremiun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPresidencial)
                    .addComponent(radioMasaje))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(btnEliminar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPropietarioActionPerformed

    private void radioMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMotoActionPerformed
        if(radioMoto.isSelected()){
            infoVehiculo.setVehiculo(tipoVehiculo.MOTO);
            radioCarro.setSelected(false);
        }
    }//GEN-LAST:event_radioMotoActionPerformed

    private void radioCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCarroActionPerformed
        if(radioCarro.isSelected()){
            infoVehiculo.setVehiculo(tipoVehiculo.CARRO);
            radioMoto.setSelected(false);
        }
    }//GEN-LAST:event_radioCarroActionPerformed

    private void radioNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNormalActionPerformed
        if(radioNormal.isSelected()){
            infoVehiculo.setLavado(tipoLavado.NORMAL);
            radioMasaje.setSelected(false);
            radioPremiun.setSelected(false);
            radioPresidencial.setSelected(false);    
        }
    }//GEN-LAST:event_radioNormalActionPerformed

    private void radioMasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMasajeActionPerformed
        if(radioMasaje.isSelected()){
            infoVehiculo.setLavado(tipoLavado.CON_MASAJE);
            radioNormal.setSelected(false);
            radioPremiun.setSelected(false);
            radioPresidencial.setSelected(false);    
        }
    }//GEN-LAST:event_radioMasajeActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        infoVehiculo.setPlaca(txtPlaca.getText());
        infoVehiculo.setPropietario(txtPropietario.getText());
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void radioPremiunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPremiunActionPerformed
        if(radioPremiun.isSelected()){
            infoVehiculo.setLavado(tipoLavado.PREMIUN);
            radioMasaje.setSelected(false);
            radioNormal.setSelected(false);
            radioPresidencial.setSelected(false);    
        }
    }//GEN-LAST:event_radioPremiunActionPerformed

    private void radioPresidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPresidencialActionPerformed
        if(radioPresidencial.isSelected()){
            infoVehiculo.setLavado(tipoLavado.PRESIDENCIAL);
            radioMasaje.setSelected(false);
            radioPremiun.setSelected(false);
            radioNormal.setSelected(false);    
        }
    }//GEN-LAST:event_radioPresidencialActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // Antes llamar funcion de calculo
        calcular();
        this.infoVehiculo.setFinalizado(true);
        dispose();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        this.infoVehiculo.setFinalizado(true);
        dispose();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radioCarro;
    private javax.swing.JRadioButton radioMasaje;
    private javax.swing.JRadioButton radioMoto;
    private javax.swing.JRadioButton radioNormal;
    private javax.swing.JRadioButton radioPremiun;
    private javax.swing.JRadioButton radioPresidencial;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPropietario;
    // End of variables declaration//GEN-END:variables
}
